name: Deploy to Server

on:
  push:
    branches:
      # - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            APP_NAME="${{ github.event.repository.name }}"
            BASE_DIR="/home/amin/User/Projects/Dotnet"

            SRC_DIR="$BASE_DIR/$APP_NAME"
            PUBLISH_DIR="$BASE_DIR/Publish/$APP_NAME"
            REPO_URL="https://github.com/Sitenes/$APP_NAME.git"

            mkdir -p "$BASE_DIR"
            mkdir -p "$PUBLISH_DIR"

            echo "Deploying $APP_NAME ..."

            # اگر repo وجود ندارد clone کن
            if [ ! -d "$SRC_DIR/.git" ]; then
              echo "Repo not found, cloning..."
              git clone "$REPO_URL" "$SRC_DIR"
            fi

            cd "$SRC_DIR"

            echo "Pulling latest code..."
            git reset --hard
            git pull origin master || git pull origin main

            echo "Publishing..."
            dotnet publish -c Release -o "$PUBLISH_DIR"

            echo "Restarting app..."
            pkill -f "$APP_NAME" || true
            nohup "$PUBLISH_DIR/$APP_NAME" > "$PUBLISH_DIR/app.log" 2>&1 &